apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ikenos-teamos
  namespace: ikenos-teamos
  labels:
    app: ikenos-teamos
    release: prometheus
spec:
  selector:
    matchLabels:
      app: ikenos-teamos
  namespaceSelector:
    matchNames:
    - ikenos-teamos 
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 5s

    