apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ikenos-teamos-prometheus-rules-latency
  namespace: ikenos-teamos
  labels:
    app: ikenos-teamos
    job: ikenos-teamos
    release: prometheus
    team: sre
spec:
  groups:
  - name: SLOs-http_request_duration_seconds
    rules:
    - alert: IkenosTeamos-LatencyBudgetBurn
      annotations:
        message: 'High requests latency budget burn for job=ikenos-teamos,latency=0.5 (current value: {{ $value }})'
      expr: |
        (
          latencytarget:http_request_duration_seconds:rate1h{job="ikenos-teamos",latency="0.5"} > (14.4*1.000000)
          and
          latencytarget:http_request_duration_seconds:rate5m{job="ikenos-teamos",latency="0.5"} > (14.4*1.000000)
        )
        or
        (
          latencytarget:http_request_duration_seconds:rate6h{job="ikenos-teamos",latency="0.5"} > (6*1.000000)
          and
          latencytarget:http_request_duration_seconds:rate30m{job="ikenos-teamos",latency="0.5"} > (6*1.000000)
        )
      labels:
        job: ikenos-teamos
        latency: "0.5"
        severity: critical
    - alert: IkenosTeamos-LatencyBudgetBurn
      annotations:
        message: 'High requests latency budget burn for job=ikenos-teamos,latency=0.5 (current value: {{ $value }})'
      expr: |
        (
          latencytarget:http_request_duration_seconds:rate1d{job="ikenos-teamos",latency="0.5"} > (3*1.000000)
          and
          latencytarget:http_request_duration_seconds:rate2h{job="ikenos-teamos",latency="0.5"} > (3*1.000000)
        )
        or
        (
          latencytarget:http_request_duration_seconds:rate3d{job="ikenos-teamos",latency="0.5"} > (1.000000)
          and
          latencytarget:http_request_duration_seconds:rate6h{job="ikenos-teamos",latency="0.5"} > (1.000000)
        )
      labels:
        job: ikenos-teamos
        latency: "0.5"
        severity: warning
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="ikenos-teamos",le="0.5",code!~"5.."}[5m]))
          /
          sum(rate(http_request_duration_seconds_count{job="ikenos-teamos"}[5m]))
        )
      labels:
        job: ikenos-teamos
        latency: "0.5"
      record: latencytarget:http_request_duration_seconds:rate5m
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="ikenos-teamos",le="0.5",code!~"5.."}[30m]))
          /
          sum(rate(http_request_duration_seconds_count{job="ikenos-teamos"}[30m]))
        )
      labels:
        job: ikenos-teamos
        latency: "0.5"
      record: latencytarget:http_request_duration_seconds:rate30m
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="ikenos-teamos",le="0.5",code!~"5.."}[1h]))
          /
          sum(rate(http_request_duration_seconds_count{job="ikenos-teamos"}[1h]))
        )
      labels:
        job: ikenos-teamos
        latency: "0.5"
      record: latencytarget:http_request_duration_seconds:rate1h
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="ikenos-teamos",le="0.5",code!~"5.."}[2h]))
          /
          sum(rate(http_request_duration_seconds_count{job="ikenos-teamos"}[2h]))
        )
      labels:
        job: ikenos-teamos
        latency: "0.5"
      record: latencytarget:http_request_duration_seconds:rate2h
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="ikenos-teamos",le="0.5",code!~"5.."}[6h]))
          /
          sum(rate(http_request_duration_seconds_count{job="ikenos-teamos"}[6h]))
        )
      labels:
        job: ikenos-teamos
        latency: "0.5"
      record: latencytarget:http_request_duration_seconds:rate6h
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="ikenos-teamos",le="0.5",code!~"5.."}[1d]))
          /
          sum(rate(http_request_duration_seconds_count{job="ikenos-teamos"}[1d]))
        )
      labels:
        job: ikenos-teamos
        latency: "0.5"
      record: latencytarget:http_request_duration_seconds:rate1d
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="ikenos-teamos",le="0.5",code!~"5.."}[3d]))
          /
          sum(rate(http_request_duration_seconds_count{job="ikenos-teamos"}[3d]))
        )
      labels:
        job: ikenos-teamos
        latency: "0.5"
      record: latencytarget:http_request_duration_seconds:rate3d